# Generated by Django 4.1.5 on 2023-01-28 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="../static"
            ),
            preserve_default=False,
        ),
    ]
