# Generated by Django 4.1.5 on 2023-01-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_task_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="image",
            field=models.ImageField(upload_to="static\\images"),
        ),
    ]
